-- =============================================================================
-- 002 — App-managed verification, one-time codes and sessions
--
-- Run after 001 in Supabase → SQL Editor. Safe to re-run.
--
-- The application now sends its own emails over SMTP and manages its own
-- tokens, so Supabase is used purely as a Postgres database:
--   * profiles no longer mirror auth.users (ids are generated here)
--   * registrations store the hash of the emailed verification token
--   * otp_challenges store an HMAC of the emailed code
--   * sessions is new: server-side sessions referenced by an httpOnly cookie
-- Existing rows are kept.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- profiles: stand-alone user table
-- ---------------------------------------------------------------------------
alter table public.profiles drop constraint if exists profiles_id_fkey;
alter table public.profiles alter column id set default gen_random_uuid();

-- ---------------------------------------------------------------------------
-- registrations: own verification token instead of a Supabase invite
-- ---------------------------------------------------------------------------
alter table public.registrations drop constraint if exists registrations_auth_user_id_fkey;
alter table public.registrations alter column auth_user_id drop not null;

-- SHA-256 of the token in the emailed link; cleared once used.
alter table public.registrations add column if not exists verification_token_hash text;
-- The profile created when the email was verified.
alter table public.registrations add column if not exists user_id uuid references public.profiles (id) on delete cascade;

create unique index if not exists registrations_verification_token_hash_key
  on public.registrations (verification_token_hash) where verification_token_hash is not null;

-- ---------------------------------------------------------------------------
-- otp_challenges: the code itself is generated by the app
-- ---------------------------------------------------------------------------
-- HMAC-SHA-256 of the code, keyed with the server secret (never the plain code).
alter table public.otp_challenges add column if not exists code_hash text;

-- ---------------------------------------------------------------------------
-- sessions: one row per signed-in browser
-- ---------------------------------------------------------------------------
create table if not exists public.sessions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles (id) on delete cascade,
  -- SHA-256 of the random token held in the httpOnly session cookie.
  token_hash   text not null unique,
  method       text not null check (method in ('EMAIL_VERIFICATION', 'ONE_TIME_CODE')),
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  revoked_at   timestamptz
);

create index if not exists sessions_user_id_idx on public.sessions (user_id);

comment on table public.sessions is 'Server-side sessions; the cookie holds a random token whose hash is stored here.';

-- Private to the server, like the other tables.
alter table public.sessions enable row level security;

-- Make the API (PostgREST) pick up the changes immediately.
notify pgrst, 'reload schema';
